on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          file: 'README.md'
          url: |
            http://arxiv.org/a/fowlie_a_1.atom2
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
